title: uSVE Simulator
description: Project documentation for uSVE, an unofficial SVE auto simulator
theme: just-the-docs

url: https://github.com/Sparkfir3/sve-auto-sim

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
